config/routes.rb
Rails.application.routes.draw do
  resources :items, :only => [:index, :create]
  delete :items, to: "items#destroy"
  root to: redirect("/items")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def create
    @item = Item.new(params.permit(:name))
    unless @item.save then flash[:alert] = "There was a problem saving the item (did you leave it blank?)" end
    redirect_to items_url
  end
  def destroy
    Item.delete_all
    redirect_to items_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<div class="content">
  <h1>Shopper - super simple shopping list</h1>
  <ul>
    <% @items.each do |item| %>
      <li><%= item.name %></li>
    <% end %>
  </ul>

  <%= form_with url: items_path  do |form| %>
    <%= form.text_field :name, placeholder: "Please enter an item", :autofocus => true %>
    <%= form.submit "+" %>
  <% end %>
  <%= link_to 'Clear list', items_path,
              data: {:confirm => 'Are you sure?'}, :method => :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>